layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects: 
      tasks,
      Akshatji800,
      hacktoberfest-2021,
      amfoss-tasks-demo

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: akshajsr000
  instagram: a_k_s_h_a_j
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: Akshajsr
  twitter: sr_akshaj
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username



topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
    
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/180320cffc25f4ed1bbdfd33d4db3a66eeeeb358/topics/cpp/cpp.png
    
  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://raw.githubusercontent.com/github/explore/cebd63002168a05a6a642f309227eefeccd92950/topics/flutter/flutter.png
    
  - name: Blockchain
    web_url: https://github.com/topics/blockchain
    image_url: https://raw.githubusercontent.com/github/explore/66e4a32f59558ad7852fca3eee52b5838a5b3cc8/topics/blockchain/blockchain.png
    
  - name: Artificial Intelligence
    web_url: https://github.com/topics/artificial-intelligence
    image_url: https://raw.githubusercontent.com/github/explore/558a9d7bbfd1683934210d9500c1e0c8b8c50f77/topics/ai/ai.png

theme: no-style-please



